# Site Title Name
title: Zaw Zaw
# Site Description
description: Passionate about Android and Linux Kernel
# Author Name
author: Zaw Zaw

# Jekyll plugins
plugins:
  - jekyll-paginate

# Paginate number and path
paginate: 7
paginate_path: /blog/page:num/

# Jekyll Theme
theme: # Set empty theme.

# MAIN URL
url: https://zawzaww.github.io

# Base URL
baseurl: ""

# Social
author: "Zaw Zaw"
twitter:
  username: zawzawwme
