title: Zaw Zaw
description: Personal Blog

baseurl: "/blog"
url: "https://zawzaww.github.io"

cayman-blog:
  date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman-blog
remote_theme: jekyll-theme-cayman-blog

# social
author: "Zaw Zaw"
image: /profile.jpg
twitter:
  username: zawzawwme
