# Site Title Name
title: "Zaw Zaw"
# Site Description
description: "ZAW's Homepage and Personal Website"

# Jekyll plugins
plugins:
  - jekyll-paginate

# Google Analytics
google_analytics:

# Paginate number and path
paginate: 7
paginate_path: /blog/page:num/

# Jekyll Theme
theme: # Set empty theme.

# jekyll-theme-cayman-blog date format
jekyll-theme-cayman-blog:
  date_format: "%B %-d, %Y"

# MAIN URL
url: https://zawzaww.github.io

# Base URL
baseurl: ""

# Social
author: "Zaw Zaw"
twitter:
  username: zawzaw_me
