# Site Title Name
title: Zaw Zaw

# Site Description
description: Passionate about Android and Linux Kernel

# Jekyll Theme
theme: jekyll-theme-minimal

# MAIN URL
url: https://zawzaww.github.io

# Base URL
baseurl: ""

# Social
author: "Zaw Zaw"
twitter:
  username: zawzawwme
