#
# The Site Configurations
#

theme: # Set empty theme

baseurl: ''

lang: en-US

title: Zaw Zaw

tagline: Systems Programmer/SRE Engineer

description: >-
  ZAW's personal blog about Systems programming, 
  Operating systems, Linux kernel and containers.

url: ''

github:
  username: zawzaww

twitter:
  username: zawzaw_me

social:
  name: Zaw Zaw
  email: zawzthein@outlook.com
  links:
    - https://twitter.com/zawzaw_me
    - https://github.com/zawzaww

google_site_verification: google_meta_tag_verification

google_analytics:
  id: ''
  pv:
    proxy_endpoint:
    cache_path:

# Prefer color scheme setting.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: dark

img_cdn: ''

avatar: https://i.postimg.cc/9XwV2NZV/zawzaw.png

toc: true

disqus:
  comments: true
  shortname: 'Zaw Zaw'

paginate: 8

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - '*.json'

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
