# Site Title Name
title: Zaw Zaw

# Site Description
description: Passionate about Android and Linux Kernel

# Jekyll plugins
plugins:
  - jekyll-paginate

# Paginate number and path
paginate: 6
paginate_path: /blog/page:num/

# Jekyll Theme
theme: # Set empty theme.

# MAIN URL
url: https://zawzaww.github.io

# Base URL
baseurl: ""

# Social
author: "Zaw Zaw"
twitter:
  username: zawzawwme
