#
# The Site Configurations
#

theme: jekyll-theme-chirpy

baseurl: ''

lang: en-US

title: Zaw Zaw

tagline: "Keep it minimal, Keep it simple."

description: ZAW's Personal Blog

plugins:
  - jekyll-paginate

url: https://zawzaww.github.io

github:
  username: zawzaww

twitter:
  username: zawzaw_me

social:
  name: Zaw Zaw
  email: zawzthein@outlook.com
  links:
    - https://twitter.com/zawzaw_me
    - https://github.com/zawzaww

google_site_verification: google_meta_tag_verification

google_analytics:
  id: ''
  pv:
    proxy_endpoint:
    cache_path:

theme_mode: light

img_cdn: ''

avatar: https://i.postimg.cc/9XwV2NZV/zawzaw.png

toc: true

disqus:
  comments: true
  shortname: 'Zaw Zaw'

paginate: 8

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
      dynamic_title: true
  -
    scope:
      path: _drafts
    values:
      comments: true
  -
    scope:
      path: ''
      type: tabs
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - '*.json'

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
