# Jekyll Theme
theme: jekyll-theme-minimal

# Name
title: < Zaw Zaw />

# MAIN URL
url: https://zawzaww.github.io/

# Base URL
# Default: empty url
baseurl: ""

# Permalink for posts and pages
# permalink: /placeholders/:title/

# Social
author: "Zaw Zaw"
twitter:
  username: zawzawwme
