# Site Title Name
title: Zaw Zaw

# Site Description
description: PureZ Kernel Project Maintainer

# Jekyll Theme
theme: jekyll-theme-minimal

# MAIN URL
url: https://zawzaww.github.io

# Base URL
baseurl: ""

# Permalink for posts and pages
# permalink: /placeholders/:title/

# Social
author: "Zaw Zaw"
twitter:
  username: zawzawwme
