# Site Title Name
title: Zaw Zaw

# Site Description
description: Passionate about Android and Linux Kernel

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: 

# Jekyll Theme
theme: # Set empty theme.

# MAIN URL
url: https://zawzaww.github.io

# Base URL
baseurl: ""

# Social
author: "Zaw Zaw"
twitter:
  username: zawzawwme
