# Site Title Name
title: Zaw Zaw
# Site Description
description: Passionate about Android and Linux Kernel
# Author Name
author: Zaw Zaw

# Jekyll plugins
plugins:
  - jekyll-paginate

# Google Analytics
google_analytics:

# Paginate number and path
paginate: 7
paginate_path: /blog/page:num/

# Jekyll Theme
theme: # Set empty theme.

# jekyll-theme-simple-blog date format
jekyll-theme-simple-blog:
  date_format: "%b %-d, %Y"

# MAIN URL
url: https://zawzaww.github.io

# Base URL
baseurl: ""

# Social
author: "Zaw Zaw"
twitter:
  username: zawzawwme

# Translation
t:
  en:
    months:
      january: "Jan"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "May"
      june: "Jun"
      july: "Jul"
      august: "Aug"
      september: "Sep"
      october: "Oct"
      november: "Nov"
      december : "Dec"

defaults:
  -
    values:
      lang: "en"
