#
# Docker compose
# for serve Jekyll site for local environment.
#
services:
  jekyll-site:
    image: jekyll-site:local
    container_name: jekyll-site
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint:
      >-
      bundle exec jekyll serve
        --host 0.0.0.0
        --port 4000
        --watch
        --drafts
        --livereload
    volumes:
      - ".:/src/jekyll"
    ports:
      - "4000:4000"
      - "35729:35729"

