#
# Docker compose
# for serve Jekyll site for local environment.
#
version: "3.3"

services:
  jekyll-site:
    image: jekyll-site:local
    container_name: jekyll-site
    build:
      context: ./
      dockerfile: Dockerfile
    command: >
      jekyll serve
        --watch
        --drafts
        --livereload
    volumes:
      - ".:/srv/jekyll"
    ports:
      - "4000:4000"
      - "35729:35729"

